name: Release Beta

on:
  push:
    branches:
      - dev

permissions:
  contents: write
  packages: write
  pull-requests: write
  issues: read

jobs:
  prettier-check:
    name: Prettier check
    uses: ./.github/workflows/prettier.yml
    if: success()

  release:
    needs: [ prettier-check ]
    name: Beta Release
    runs-on: ubuntu-latest
    env:
      DOCKER_REGISTRY_USER: ${{ secrets.DOCKER_REGISTRY_USER }}
      DOCKER_REGISTRY_PASSWORD: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm i

      - name: Release (beta)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: node_modules/.bin/semantic-release
